import type { Metadata } from "next";
import { LegalLayout } from "../legal-layout";

export const metadata: Metadata = {
  title: "Política de Privacidade | Arquivio",
  description: "Como o Arquivio acessa, usa, armazena e exclui dados pessoais e documentos conectados.",
};

export default function PrivacyPage() {
  return <LegalLayout title="Política de Privacidade">
    <section><h2>1. Quem é responsável</h2><p>O Arquivio é um serviço operado por Vitor Perez. Para dúvidas, solicitações de privacidade ou exclusão de dados, escreva para <a href="mailto:lagevitor.dev@gmail.com">lagevitor.dev@gmail.com</a>. Quando uma organização conecta documentos de sua equipe, ela decide quais conteúdos serão compartilhados no serviço; o Arquivio trata esses dados para prestar as funcionalidades contratadas.</p></section>
    <section><h2>2. Dados que tratamos</h2><ul><li>Dados de conta e organização, como nome, e-mail, vínculo com a equipe, função e informações de autenticação fornecidas pelo serviço de login.</li><li>Dados das integrações Google Drive, Microsoft OneDrive, Microsoft SharePoint (Microsoft 365) e Notion: identificação da conta conectada, credenciais de acesso e metadados necessários à seleção e sincronização.</li><li>Texto extraído, trechos, índices de busca e vetores dos documentos sincronizados. Os arquivos originais permanecem no provedor de origem.</li><li>Consultas que o usuário escolhe salvar, com seus filtros; contadores de uso e registros de auditoria. Perguntas e trechos recuperados são processados para gerar a resposta e suas referências, mas o Arquivio não mantém um histórico persistente dessas perguntas, respostas ou referências.</li></ul></section>
    <section><h2>3. Como usamos os dados</h2><p>Usamos esses dados para autenticar usuários, manter a biblioteca, sincronizar os conteúdos escolhidos, permitir buscas e gerar respostas com referências. Também os usamos para segurança, suporte, diagnóstico de falhas e cumprimento de obrigações legais. O conteúdo sincronizado fica disponível aos membros autorizados da mesma organização; por isso, o administrador deve conectar apenas materiais que possam ser compartilhados com a equipe.</p><p>A sincronização e o processamento ocorrem em segundo plano. As respostas consideram o conteúdo já indexado e podem estar desatualizadas até a próxima sincronização bem-sucedida.</p></section>
    <section><h2>4. Integrações e uso de dados do Google</h2><p>Ao conectar o Google Drive, solicitamos a permissão OAuth <code>drive.readonly</code>, que permite visualizar e baixar todos os arquivos do Drive aos quais a conta conectada tem acesso. A escolha posterior de pastas, arquivos ou de todo o conteúdo acessível delimita o que o Arquivio sincroniza e indexa internamente; ela não reduz a permissão concedida pelo Google. A listagem de arquivos e pastas para escolher o escopo usa metadados disponíveis por essa permissão. Para OneDrive, SharePoint e Notion, o acesso também depende da autorização concedida ao respectivo provedor. No SharePoint, o acesso é somente leitura e segue as permissões da conta de administrador que conecta; todos os membros da organização no Arquivio poderão consultar o conteúdo indexado das bibliotecas escolhidas, mesmo que no SharePoint ele tenha permissões diferentes. Não alteramos os arquivos originais, não usamos dados obtidos pelas APIs do Google para publicidade e não os vendemos.</p><p>O conteúdo indexado pode ser consultado pelos membros da organização autorizados no Arquivio. As funções de suporte implementadas para a equipe da plataforma expõem metadados da organização e do estado de sincronização, sem leitura de conteúdo de documentos, perguntas ou respostas. Ao desconectar uma fonte, as credenciais salvas são removidas e novas sincronizações por essa conexão deixam de ocorrer. A desconexão não apaga o conteúdo já indexado; administradores podem remover documentos ou escopos locais pela biblioteca. A autorização também pode ser revogada nas configurações do provedor.</p></section>
    <section><h2>5. Compartilhamento e fornecedores</h2><p>O Arquivio usa provedores de infraestrutura e processamento para oferecer o serviço, incluindo Railway (hospedagem e banco de dados), WorkOS (autenticação), OpenAI (processamento de texto para busca e respostas) e Resend (e-mails de convite). O conteúdo necessário à pergunta ou à indexação pode ser enviado ao provedor de IA. Google, Microsoft e Notion recebem as solicitações necessárias para acessar os materiais autorizados. Esses fornecedores podem processar dados em outros países, conforme seus serviços e contratos.</p></section>
    <section><h2>6. Armazenamento, segurança e prazo</h2><p>Credenciais de integração são armazenadas de forma criptografada. O serviço ainda não tem uma política implementada de prazo fixo para eliminar automaticamente sessões expiradas, estados OAuth, trabalhos, registros de auditoria ou conteúdo indexado após desconexão. A remoção de um escopo da biblioteca apaga seus documentos, trechos, vetores, consultas salvas e trabalhos associados do banco ativo; desconectar uma fonte remove suas credenciais, mas conserva o índice até a remoção do escopo. Ainda não há prazo de retenção ou eliminação de cópias de segurança verificado para informar nesta página.</p></section>
    <section><h2>7. Seus direitos e exclusão</h2><p>Para solicitar acesso, correção, informação sobre compartilhamento ou exclusão de dados pessoais, envie um e-mail para <a href="mailto:lagevitor.dev@gmail.com">lagevitor.dev@gmail.com</a>, indicando a organização e o e-mail da conta. Solicitações de exclusão de dados da conta ou da organização são avaliadas por esse contato; não há fluxo automático verificado para esses pedidos. Podemos confirmar sua identidade e a autoridade do administrador antes de alterar dados de uma organização.</p></section>
    <section><h2>8. Alterações</h2><p>Esta política pode ser atualizada quando o serviço ou suas práticas mudarem. A versão vigente ficará nesta página, com a data de atualização.</p></section>
  </LegalLayout>;
}
