import type { Metadata } from "next";
import { LegalLayout } from "../legal-layout";

export const metadata: Metadata = {
  title: "Política de Privacidade | Arquivio",
  description: "Como o Arquivio acessa, usa, armazena e exclui dados pessoais e documentos conectados.",
};

export default function PrivacyPage() {
  return <LegalLayout title="Política de Privacidade">
    <section><h2>1. Quem é responsável</h2><p>O Arquivio é um serviço operado por Vitor Perez. Para dúvidas, solicitações de privacidade ou exclusão de dados, escreva para <a href="mailto:lagevitor.dev@gmail.com">lagevitor.dev@gmail.com</a>. Quando uma organização conecta documentos de sua equipe, ela decide quais conteúdos serão compartilhados no serviço; o Arquivio trata esses dados para prestar as funcionalidades contratadas.</p></section>
    <section><h2>2. Dados que tratamos</h2><ul><li>Dados de conta e organização, como nome, e-mail, vínculo com a equipe, função e informações de autenticação fornecidas pelo serviço de login.</li><li>Dados das integrações Google Drive, Microsoft OneDrive e Notion: identificação da conta conectada, autorização de acesso e metadados dos itens selecionados.</li><li>Texto extraído, trechos, índices de busca e vetores dos documentos autorizados para sincronização. Os arquivos originais permanecem no provedor de origem.</li><li>Perguntas, consultas salvas, referências usadas nas respostas, registros de uso e eventos técnicos necessários para operar, proteger e diagnosticar o serviço.</li></ul></section>
    <section><h2>3. Como usamos os dados</h2><p>Usamos esses dados para autenticar usuários, manter a biblioteca, sincronizar os conteúdos escolhidos, permitir buscas e gerar respostas com referências. Também os usamos para segurança, suporte, diagnóstico de falhas e cumprimento de obrigações legais. O conteúdo sincronizado fica disponível aos membros autorizados da mesma organização; por isso, o administrador deve conectar apenas materiais que possam ser compartilhados com a equipe.</p><p>A sincronização e o processamento ocorrem em segundo plano. As respostas consideram o conteúdo já indexado e podem estar desatualizadas até a próxima sincronização bem-sucedida.</p></section>
    <section><h2>4. Integrações e uso de dados do Google</h2><p>O acesso aos provedores depende de autorização do usuário e é usado somente para ler os arquivos e páginas incluídos no escopo escolhido, processá-los e oferecer busca e respostas no Arquivio. Não alteramos os arquivos originais, não usamos dados obtidos pelas APIs do Google para publicidade e não os vendemos. Não permitimos que pessoas leiam esses dados, exceto quando isso for necessário para suporte ou segurança com autorização, para cumprir a lei ou quando o conteúdo for compartilhado pelo próprio usuário com sua organização.</p><p>Ao desconectar uma fonte, o Arquivio deixa de usar a autorização salva para novas sincronizações. A desconexão, por si só, não apaga o conteúdo já indexado; para removê-lo, o administrador pode excluir os itens ou escopos da biblioteca, ou solicitar a exclusão pelo contato abaixo. A autorização também pode ser revogada nas configurações do provedor.</p></section>
    <section><h2>5. Compartilhamento e fornecedores</h2><p>O Arquivio usa provedores de infraestrutura e processamento para oferecer o serviço, incluindo Railway (hospedagem e banco de dados), WorkOS (autenticação), OpenAI (processamento de texto para busca e respostas) e Resend (e-mails de convite). O conteúdo necessário à pergunta ou à indexação pode ser enviado ao provedor de IA. Google, Microsoft e Notion recebem as solicitações necessárias para acessar os materiais autorizados. Esses fornecedores podem processar dados em outros países, conforme seus serviços e contratos.</p></section>
    <section><h2>6. Armazenamento, segurança e prazo</h2><p>Credenciais de integração são armazenadas de forma criptografada. Mantemos dados de conta e conteúdo indexado enquanto a organização usa o serviço ou enquanto forem necessários às finalidades descritas. Dados podem permanecer por tempo adicional quando exigido por lei, para segurança ou em cópias de segurança até sua substituição. Ainda não oferecemos eliminação automática por prazo fixo; pedidos de exclusão são tratados individualmente pelo contato abaixo.</p></section>
    <section><h2>7. Seus direitos e exclusão</h2><p>Para pedir acesso, correção, portabilidade, informação sobre compartilhamento ou exclusão de dados pessoais, envie um e-mail para <a href="mailto:lagevitor.dev@gmail.com">lagevitor.dev@gmail.com</a>, indicando a organização e o e-mail da conta. Podemos confirmar sua identidade e a autoridade do administrador antes de alterar dados de uma organização. Se a solicitação envolver documentos da equipe, também poderemos encaminhá-la ao administrador responsável. Responderemos conforme os prazos legais aplicáveis.</p></section>
    <section><h2>8. Alterações</h2><p>Esta política pode ser atualizada quando o serviço ou suas práticas mudarem. A versão vigente ficará nesta página, com a data de atualização.</p></section>
  </LegalLayout>;
}
