"use client";

import { ChevronRight, CircleAlert, Plus } from "lucide-react";
import { FormEvent, useState } from "react";
import { Brand } from "../brand";
import { type Role, type Company, type User, ApiError, api, isInvitationToken, messageFor } from "./types-and-api";
import { LoadingIndicator } from "./shared-ui";

export function Loading() { return <main className="auth-page"><div className="text-center"><Brand /><LoadingIndicator label="Preparando seu espaço de conhecimento…" className="mt-3 justify-center text-sm text-muted-foreground" /></div></main>; }
export { SignIn } from "./custom-login";
export function InvitationAcceptance({ token, onAccepted }: { token: string | undefined; onAccepted: (organizationId: string) => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  if (!isInvitationToken(token)) return <main className="auth-page"><section className="max-w-md text-center"><CircleAlert className="mx-auto text-amber-300" size={34} /><h1 className="mt-4 text-2xl font-semibold">Convite indisponível</h1><p className="mt-3 text-muted-foreground">Este link não é válido. Peça um novo convite à pessoa responsável pela organização.</p></section></main>;
  async function accept() { setBusy(true); setError(null); try { const accepted = await api<{ organization_id: string }>(`/invitations/${encodeURIComponent(token ?? "")}/accept`, { method: "POST" }); onAccepted(accepted.organization_id); } catch (caught) { setError(caught instanceof ApiError && caught.status === 404 ? "Este convite expirou, já foi usado ou não pertence ao seu e-mail." : messageFor(caught)); } finally { setBusy(false); } }
  return <main className="auth-page"><section className="auth-card"><Brand /><p className="mt-6 text-sm font-semibold text-primary">Convite para uma organização</p><h1 className="mt-2 text-3xl font-semibold">Participar da equipe</h1><p className="mt-3 leading-6 text-muted-foreground">Ao aceitar, você terá acesso aos recursos compartilhados com os membros desta organização.</p>{error && <p className="mt-4 rounded-md border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<button disabled={busy} onClick={() => { void accept(); }} className="mt-7 w-full rounded-md bg-primary px-4 py-3 font-semibold text-primary-foreground disabled:opacity-50">{busy ? "Aceitando…" : "Aceitar convite"}</button></section></main>;
}
export function Onboarding({ user, onCreated }: { user: User; onCreated: (company: Company) => void }) {
  const [name, setName] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function create(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const created = await api<{ id: string; membership_id: string; role: Role }>("/organizations", { method: "POST", body: JSON.stringify({ name: name.trim() }) }); onCreated({ ...created, name: name.trim() }); } catch (caught) { setError(messageFor(caught)); } finally { setBusy(false); } }
  return <main className="auth-page"><section className="auth-card"><Brand /><p className="mt-6 text-sm text-muted-foreground">{user.email}</p><h1 className="mt-2 text-3xl font-semibold">Crie sua primeira organização</h1><p className="mt-3 leading-6 text-muted-foreground">Reúna os documentos da sua equipe em um só lugar. Depois, conecte uma fonte de arquivos e convide as pessoas com quem você trabalha.</p><form onSubmit={create} className="mt-7"><label htmlFor="company-name" className="text-sm font-medium">Nome da organização</label><input id="company-name" required maxLength={160} value={name} onChange={(event) => setName(event.target.value)} placeholder="Ex.: Estúdio Aurora" className="mt-2 w-full rounded-md border border-line bg-panel px-4 py-3 outline-none ring-primary focus:ring-2" aria-describedby={error ? "company-name-error" : undefined} />{error && <p id="company-name-error" role="alert" className="mt-3 text-sm text-rose-700">{error}</p>}<button disabled={busy || !name.trim()} aria-busy={busy} className="mt-5 inline-flex items-center gap-2 rounded-md bg-primary px-5 py-3 font-semibold text-primary-foreground disabled:opacity-50"><Plus size={17} aria-hidden="true" />{busy ? "Criando…" : "Criar organização"}</button></form></section></main>;
}
export function InvalidCompany({ companies, onChoose }: { companies: Company[]; onChoose: (id: string) => void }) { return <main className="auth-page"><section className="max-w-md text-center"><CircleAlert className="mx-auto text-amber-300" size={34} /><h1 className="mt-4 text-2xl font-semibold">Esta organização não está disponível</h1><p className="mt-3 text-muted-foreground">Você não tem acesso a este espaço ou ele não está mais disponível. Escolha uma organização da qual você participa.</p><div className="mt-6 space-y-2">{companies.map((company) => <button key={company.id} onClick={() => onChoose(company.id)} className="flex w-full items-center justify-between rounded-md border border-line bg-panel px-4 py-3 text-left hover:bg-sage"><span>{company.name}</span><ChevronRight size={16} /></button>)}</div></section></main>; }
