// Local fixture only. All auth requests go to preview_gateway.py, never WorkOS.
import { chromium } from "/Users/vitorperez/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs";
import assert from "node:assert/strict";
import { writeFileSync } from "node:fs";

const browser = await chromium.launch({ headless: true, executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" });
const evidence = { environment: "local fixture only; no real authentication or email", viewports: [], flows: [] };
try {
  for (const width of [1280, 390, 320]) {
    const context = await browser.newContext({ viewport: { width, height: 900 } });
    const page = await context.newPage();
    const response = await page.goto("http://localhost:3117/login");
    await page.getByLabel("E-mail", { exact: true }).waitFor();
    assert.equal(await page.locator('[role="alert"]').count(), 0);
    const dimensions = await page.evaluate(() => ({ viewport: window.innerWidth, content: document.documentElement.scrollWidth }));
    assert.equal(dimensions.viewport, width);
    assert.ok(dimensions.content <= width, JSON.stringify(dimensions));
    assert.equal(response.headers()["referrer-policy"], "no-referrer");
    assert.equal(await page.locator('meta[name="referrer"]').getAttribute("content"), "no-referrer");
    await page.screenshot({ path: new URL(`login-${width}.png`, import.meta.url).pathname, fullPage: true });
    evidence.viewports.push({ width, ...dimensions, referrerPolicy: "no-referrer", noSessionError: true });
    await context.close();
  }
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto("http://localhost:3117/login?mode=sign-up");
  await page.getByLabel("E-mail", { exact: true }).fill("demo@example.com");
  assert.equal(await page.locator('input[name="password"]').count(), 0);
  await page.getByRole("button", { name: "Criar minha conta" }).click();
  await page.getByRole("status").filter({ hasText: "Confira seu e-mail" }).waitFor();
  evidence.flows.push("signup asks email only; ownership-link notice; no authenticated session");
  const resetReferers = [];
  page.on("request", request => { if (request.headers()["referer"]) resetReferers.push(request.headers()["referer"]); });
  await page.goto("http://localhost:3117/login?token=preview-only");
  await page.getByLabel("Nova senha", { exact: true }).waitFor();
  await page.waitForFunction(() => !new URL(location.href).searchParams.has("token"));
  await page.getByLabel("Nova senha", { exact: true }).fill("preview-password");
  await page.getByRole("button", { name: "Salvar nova senha" }).click();
  await page.waitForURL(/password_reset=1/);
  await page.getByRole("status").filter({ hasText: "Senha atualizada" }).waitFor();
  assert.ok(resetReferers.every(value => !value.includes("preview-only")));
  evidence.flows.push("reset token removed from URL before submit; no reset token in Referer; reset success returns to login");
  await page.getByLabel("E-mail", { exact: true }).fill("demo@example.com");
  await page.getByLabel("Senha", { exact: true }).fill("preview-password");
  await page.getByRole("button", { name: "Entrar", exact: true }).click();
  await page.waitForURL("http://localhost:3117/");
  evidence.flows.push("password login creates fixture session and navigates to app onboarding");
  await context.close();
  const verificationContext = await browser.newContext();
  const verificationPage = await verificationContext.newPage();
  await verificationPage.goto("http://localhost:3117/login");
  await verificationPage.getByLabel("E-mail", { exact: true }).fill("verify@example.com");
  await verificationPage.getByLabel("Senha", { exact: true }).fill("preview-password");
  await verificationPage.getByRole("button", { name: "Entrar", exact: true }).click();
  await verificationPage.getByLabel("Código de confirmação").waitFor();
  await verificationPage.getByRole("button", { name: "Reenviar código" }).click();
  await verificationPage.getByRole("status").filter({ hasText: "Novo código solicitado" }).waitFor();
  await verificationPage.getByLabel("Código de confirmação").fill("123456");
  await verificationPage.getByRole("button", { name: "Confirmar e entrar" }).click();
  await verificationPage.waitForURL("http://localhost:3117/");
  evidence.flows.push("verification, authenticated resend and fixture code accepted");
  await verificationContext.close();
  const fallbackContext = await browser.newContext();
  const fallbackPage = await fallbackContext.newPage();
  const invitation = "/invitations/" + "a".repeat(43);
  await fallbackPage.goto(`http://localhost:3117/login?return_to=${encodeURIComponent(invitation)}`);
  await fallbackPage.route("**/api/auth/login?*", route => route.abort());
  const fallbackRequest = fallbackPage.waitForRequest(request => request.url().includes("/api/auth/login?"));
  await fallbackPage.getByRole("button", { name: "Continuar com SSO ou outro método" }).click();
  assert.equal(new URL((await fallbackRequest).url()).searchParams.get("return_to"), invitation);
  evidence.flows.push("hosted fallback from /login preserves validated invitation return_to");
  await fallbackContext.close();
  const radarContext = await browser.newContext();
  const radarPage = await radarContext.newPage();
  await radarPage.goto("http://localhost:3117/login");
  await radarPage.getByLabel("E-mail", { exact: true }).fill("radar@example.com");
  await radarPage.getByLabel("Senha", { exact: true }).fill("incorrect-password");
  await radarPage.getByRole("button", { name: "Entrar", exact: true }).click();
  await radarPage.getByRole("alert").waitFor();
  assert.equal(await radarPage.getByRole("status").count(), 0);
  await radarPage.getByLabel("Senha", { exact: true }).fill("preview-password");
  await radarPage.getByRole("button", { name: "Entrar", exact: true }).click();
  await radarPage.getByRole("status").filter({ hasText: "etapa adicional de segurança" }).waitFor();
  assert.equal(await radarPage.getByRole("alert").count(), 0);
  await radarPage.route("**/api/auth/login?*", route => route.abort());
  const radarRequest = radarPage.waitForRequest(request => request.url().includes("/api/auth/login?"));
  await radarPage.getByRole("button", { name: "Continuar com SSO ou outro método" }).click();
  await radarRequest;
  evidence.flows.push("invalid credential remains alert; Radar fixture shows hosted fallback without session");
  await radarContext.close();
  writeFileSync(new URL("browser-smoke.json", import.meta.url), JSON.stringify(evidence, null, 2) + "\n");
  console.log(JSON.stringify(evidence));
} finally { await browser.close(); }
